version: '3.7'
services:
  api:
    container_name: pp-api
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    image: pp-api:latest
    ports:
      - '8080:8080'
    environment:
      - TZ=Asia/Bangkok