version: '3.7'
services:
  db:
    container_name: pp-db
    image: mongo
    volumes:
      - pp_db:/data/db
    ports:
      - '27017:27017'
    environment:
      - TZ=Asia/Bangkok
      
volumes:
  pp_db:
